export const FORGOT_REQUEST = 'auth/FORGOT_REQUEST';
export const FORGOT_SUCCESS = 'auth/FORGOT_SUCCESS';
export const FORGOT_FAILURE = 'auth/FORGOT_FAILURE';
export const RESET_FORGOT_MESSAGE = 'auth/RESET_FORGOT_MESSAGE';
